name: nerdyweirdwords

networks:
  nerdyweirdwords:
    driver: bridge

services:

  database:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: nerdyweirdwords
    networks:
      - nerdyweirdwords
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./NerdyWeirdWordsBackend
    networks:
      - nerdyweirdwords
    ports:
      - "65535:8080"

  frontend:
    build:
      context: ./NerdyWeirdWords
    networks:
      - nerdyweirdwords
    ports:
      - "65534:3000"

volumes:
  database:

